version: '3.5'

services:
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - '5333:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_api

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '9000:80'
    depends_on:
      - db

volumes:
  db:

networks:
  default:
    name: postgres-network
